import 'anime.dart';

const animeList = [
  Anime(
    title: 'Stranger things',
    description: 'Мальчик Уилла Байерс исчезает по пути домой осенью 1983 года, его друзья, ушедшие на его поиски, встречают девочку из лаборатории, которая поможет им с поисками.',
    genre: 'Триллер, психология',
    year:2015,
    rating: 9.0,
    imagePath: 'assets/images/movie1.jpg',
  ),
  Anime(
    title: 'Maze runner',
    description: 'Подростки оказываются запертыми в лабиринте без представления о внешнем мире.',
    genre: 'Путешествия, драма',
    year: 2014,
    rating: 8.5,
    imagePath: 'assets/images/movie2.jpg',
  ),
  Anime(
    title: 'Euphoria',
    description: 'История о подростках, что пытаются найти себя в мире, совершая ошибки, каждая из которых отзовется им в будущем.',
  genre: 'Драма',
  year: 2019,
  rating: 8.3,
  imagePath: 'assets/images/movie3.jpg',
  ),
  Anime(
    title: 'the Boys',
    description: 'Сатирическая комедия с прымой отсылкой на современный мир.',
    genre: 'Приключения, Комедия',
    year: 2019,
    rating: 8.9,
    imagePath: 'assets/images/movie4.png',
  ),
  Anime(
    title: 'Game of thrones',
    description: 'Культовый сериал о политике, семейных связях и борьбе за власть и место в этом мире.',
    genre: 'Приключения, Фэнтези, Драма',
    year: 2011,
    rating: 8.7,
    imagePath: 'assets/images/movie5.jpg',
  ),
  Anime(
    title: 'Hunger games',
    description: 'Серия фильмов, снятая по бестселлеру жанра антиутопии, рассказывает о мире, где подростков отправляют играть в убийственные игры на потеху публике..',
    genre: 'Экшен, драма',
    year: 2014,
    rating: 8.4,
    imagePath: 'assets/images/movie6.jpg',
  ),
  Anime(
    title: 'Maleficent',
    description: 'Другой взгляд на знаменитую диснеевскую злодейку.',
    genre: 'Фэнтези, Приключения',
    year: 2015,
    rating: 7.7,
    imagePath: 'assets/images/movie7.jpg',
  ),
  Anime(
    title: 'Ready player one',
    description: 'История о мире, где главным местом обитания человека стал виртуальный мир, а игровая валюта заменила реальную.',
    genre: 'Экшен, Sci-fi',
    year: 2018,
    rating: 9.1,
    imagePath: 'assets/images/movie8.jpg',
  ),
  Anime(
    title: 'Chernobyl',
    description: 'Художественный фильм, снятый на реальных событиях Чернобыльской катастрофы.',
    genre: 'Ужасы, Экшен',
    year: 2019,
    rating: 7.9,
    imagePath: 'assets/images/movie9.jpg',
  ),
  Anime(
    title: 'Достать ножи',
    description: 'Детективная семейная драма о расследовании убийства и дележке наследства.',
    genre: 'Детектив, Триллер',
    year: 2019,
    rating: 9.1,
    imagePath: 'assets/images/movie10.jpg',
  ),

];